### ISSUE TITLE
你好，汽车之家爬虫问题咨询

### ISSUE THREAD

**Issue by alasai** [LittleLory/codePool#1]
spec 这个爬虫和 detail 这个爬虫有什么区别了，看了你的注释都是汽车参数配置爬取

**Comment by LittleLory** [comment]
spec是爬基本的车型参数，也就是车型页中，“车型首页”那个tab里的车身尺寸、综合油耗等参数；detail是爬“参数配置”那个tab里的参数项和配置项数据。
ps：detail这个部分仅供参考，因为这个页面有反爬策略，爬下来的数据不能直接用。

**Comment by alasai** [comment]
恩恩运行了detail爬虫，里面的汉字都被css 伪类替换了

**Comment by alasai** [comment]
正在想办法怎么破解这个css伪类

**Comment by LittleLory** [comment]
可以试试用selenium，动态执行js来获取。效率低一些，但勉强可以用。具体的细节我就不说了👻

**Comment by alasai** [comment]
恩我试看看吧，谢了
